#!/bin/sh

set -e

echo "building release tarball"
pwd
ls -la

echo "user-service" > ./prepared-release/name
echo "v0.0.1" > ./prepared-release/tag

tar -cvzf ./prepared-release/user.tgz /user

ls -la ./prepared-release/user.tgz