#!/bin/sh

set -e

echo "Building Release Tarball"
pwd
ls -la

echo $APP_NAME > ./prepared-release/name
echo $APP_VERSION > ./prepared-release/tag

echo "Name ="
cat ./prepared-release/name
echo "Version = "
cat ./prepared-release/tag

